language: node_js
cache:
  directories:
    - node_modules
    - data
script:
  - npm run generate-data
  - npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  on:
    branch: master