language: node_js
cache:
  directories:
    - node_modules
    - data
install:
  - npm ci
  - npm install -g codecov
script:
  - npm run generate-data
  - npm run test
  - codecov
  - npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  on:
    branch: master